# -*- coding: utf-8 -*-
"""app1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WCcFGQO9WRjHnhtwco3W6cBk3Xp2l2pR
"""

import streamlit as st
import pandas as pd


# 加载数据
df = pd.read_csv("population_cbd.csv")

# 标题
st.title("Melbourne CBD Population Growth Dashboard")

# 用户交互：年份范围选择
year_range = st.slider("Select year range", 2010, 2025, (2015, 2022))
df_filtered = df[(df['year'] >= year_range[0]) & (df['year'] <= year_range[1])]

# 显示折线图
st.subheader("Population Over Selected Years")
st.line_chart(df_filtered.set_index("year")["population"])

# 显示年增长率
growth = df_filtered['population'].pct_change().mean() * 100
st.subheader("Average Annual Growth Rate")
st.write(f"{growth:.2f}%")
